version: '1.0.{build}'

image: Visual Studio 2017

platform:
  - x64
 
configuration:
  - Release
  - Debug

before_build:
    - cd ./cfsched
    - cmake -G "Visual Studio 15 2017 Win64" . -Dtest=ON
    - dir

build:
  project: $(APPVEYOR_BUILD_FOLDER)\cfsched\$(APPVEYOR_PROJECT_NAME).sln

test_script:
  - '.\tests\%CONFIGURATION%\tests.exe'
